# Intro

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,4,5,6,1,312312]],np.int32)

In [3]:
myarr[0,1]

4

In [4]:
myarr.shape

(1, 6)

In [5]:
myarr.dtype

dtype('int32')

In [6]:
myarr[0,1] = 43

In [7]:
myarr[0,1]

43

In [8]:
myarr

array([[     3,     43,      5,      6,      1, 312312]])

# Array Creation

In [9]:
larr = np.array([[1,2,3],[3,4,5],[4,5,6],[1,4,5]])

In [10]:
larr

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6],
       [1, 4, 5]])

How much elements present

In [11]:
larr.size

12

Dimentions and elements

In [12]:
larr.shape

(4, 3)

In [13]:
larr.dtype

dtype('int32')

In [14]:
np.array({23,4,4,2})

array({2, 4, 23}, dtype=object)

Make array of zeros

In [15]:
zeros = np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Make array of given number

In [17]:
rng = np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

start end dividations or elements

In [19]:
lspace = np.linspace(1,10,4)

In [20]:
lspace

array([ 1.,  4.,  7., 10.])

Create a random numbers array

In [21]:
emp = np.empty((4,6))

In [22]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.37961641e-306,
        1.00132483e-307, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.11259940e-306,
        1.11261774e-306, 1.78019625e-306, 1.11261774e-306],
       [1.78019625e-306, 6.89805151e-307, 7.56592338e-307,
        6.89807188e-307, 1.11261774e-306, 1.78019625e-306],
       [8.90098127e-307, 8.45559303e-307, 1.06811422e-306,
        1.05694828e-307, 1.42410974e-306, 2.22507386e-306]])

can add some array to it

In [23]:
emp_like = np.empty_like(lspace)

In [24]:
emp_like

array([ 1.,  4.,  7., 10.])

45 to 45 dimentions and array with 1 from start to end diagonally

In [25]:
ide = np.identity(45)

In [26]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
ide.shape

(45, 45)

In [28]:
arr = np.arange(99)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

Reshape the array from 1 to multiple dimentions but it should be multiple by the number of elements present in the array

In [30]:
arr = arr.reshape(3,33)

In [31]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

dedimensify the array

In [32]:
arr = arr.ravel()

In [33]:
arr.shape

(99,)

# Axis

there are multiple arrays axis so we can access them by axis


In [34]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
ar.sum(axis=1)

array([ 6, 15, 24])

Transpose

In [37]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
ar.flat

flats the elements in the array

In [39]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


Dimensions of the array

In [40]:
ar.ndim

2

Total bytes consumed

In [41]:
ar.nbytes

36

In [42]:
one = np.array([1,689,5,112,4])

Checks the highest number in the array

In [43]:
one.argmax()

1

Checks the lowest number in array

In [44]:
one.argmin()

0

Sorts the array and gives the index

In [45]:
one.argsort()

array([0, 4, 2, 3, 1], dtype=int64)

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [48]:
ar.argmin()

0

In [49]:
ar.argmax()

8

In [50]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [51]:
ar2 = np.array([[1, 2, 3],
                [4, 0, 6],
                [7, 1, 9]])

In [52]:
ar + ar2

array([[ 2,  4,  6],
       [ 8,  5, 12],
       [14,  9, 18]])

In [53]:
ar * ar2

array([[ 1,  4,  9],
       [16,  0, 36],
       [49,  8, 81]])

In [54]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [55]:
ar.sum()

45

In [56]:
ar.max()

9

In [57]:
ar.min()

1

In [58]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.count_nonzero(ar)

9

In [61]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))